// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoPractico.Models;

#nullable disable

namespace TrabajoPractico.Migrations
{
    [DbContext(typeof(appDBcontext))]
    [Migration("20220929232758_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("TrabajoPractico.Models.Autor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("autores");
                });

            modelBuilder.Entity("TrabajoPractico.Models.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("generos");
                });

            modelBuilder.Entity("TrabajoPractico.Models.Libro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("autorid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("generoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("resumen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("autorid");

                    b.HasIndex("generoid");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("TrabajoPractico.Models.Libro", b =>
                {
                    b.HasOne("TrabajoPractico.Models.Autor", "autor")
                        .WithMany()
                        .HasForeignKey("autorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrabajoPractico.Models.Genero", "genero")
                        .WithMany()
                        .HasForeignKey("generoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("autor");

                    b.Navigation("genero");
                });
#pragma warning restore 612, 618
        }
    }
}
